---

# Tell database master to update all databases
# FIXME: This shouldn't go to /tmp. Also it should be pushed to a backup server
#        and maybe we should use incremental backups (patches) to limit size.
- name: Backup all databases prior to running update.php
  mysql_db:
    state: dump
    name: all
    target: /tmp/full_backup_{{ ansible_date_time.iso8601 }}.sql
  delegate_to: "{{ groups['db-master'][0] }}"

# FIXME: this is a different method for getting all wikis from mediawiki/tasks/main.yml,
# which gets all databases starting with "wiki_". Probably should pick one method.
- name: Get all wikis currently installed on server
  find:
    paths: "{{ m_htdocs }}/wikis"
    file_type: directory
  register: wiki_dirs

- name: Run update.php on all wikis
  shell: WIKI={{ item.path | basename }} php {{ m_mediawiki }}/maintenance/update.php --quick
  with_items: wiki_dirs
