---


- name: Get individual wikis from controller config
  find:
    paths: "{{ m_local_public }}/wikis/"
    file_type: directory
  register: wiki_dirs
  delegate_to: localhost

- name: Ensure backups directory exists for environment
  file:
    path: "{{ m_backups }}/{{ env }}"
    state: directory
    mode: "{{ m_backups_mode }}"
    owner: "{{ m_backups_owner }}"
    group: "{{ m_backups_group }}"

- name: Ensure backups directory exists for each wiki
  file:
    path: "{{ m_backups }}/{{ env }}/{{ item }}"
    state: directory
    mode: "{{ m_backups_mode }}"
    owner: "{{ m_backups_owner }}"
    group: "{{ m_backups_group }}"
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"

- name: "Run role:rsync - Copy SQL files to backups"
  include_role:
    name: rsync
  vars:
    pulling_to_server:   "{{ inventory_hostname }}"
    pulling_to_path:     "{{ m_backups }}/{{ env }}/{{ item }}/{{ backup_timestamp }}_wiki.sql"
    pulling_from_server: "{{ groups['db-master'][0] }}"
    pulling_from_path:   "{{ m_tmp }}/{{ env }}_{{ item }}.sql"
    pulling_from_user:   "meza-ansible"
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"

# Remove temp SQL files, only needs to be done on first backup server
- name: Remove SQL files from DB master {{ m_tmp }}
  file:
    path: "{{ m_tmp }}/{{ env }}_{{ item }}.sql"
    state: absent
  delegate_to: "{{ groups['db-master'][0] }}"
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"
  run_once: true

- name: "Clean out all but the latest SQL backup file for {{ item }} IF DESIRED"
  include_role:
    name: sql-backup-cleanup
  vars:
    cleanup_wiki: "{{ item }}"
  run_once: true
  tags:
    - sql-backup-cleanup
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"
  when: do_cleanup_sql_backup
