---


- name: Get individual wikis from controller config
  find:
    paths: "{{ m_local_control }}/wikis/"
    file_type: directory
  register: wiki_dirs
  delegate_to: localhost

# FIXME: option to wipe files clean before sync? If so, do it before pulling SQL file

- name: Ensure backups directory exists for environment
  file:
    path: "{{ m_backups }}/{{ env }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure backups directory exists for each wiki
  file:
    path: "{{ m_backups }}/{{ env }}/{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"

- name: Ensure backups uploads directory exists for each wiki
  file:
    path: "{{ m_backups }}/{{ env }}/{{ item }}/uploads"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"

# copy from server A (app.0) to server B (backups)
- name: Copy uploads directories to backups
  synchronize:
    # copy from server A
    src: "{{ m_uploads_dir }}/{{ item }}/"
    # copy to server B
    dest: "{{ m_backups }}/{{ env }}/{{ item }}/uploads"
    recursive: yes
  # server A
  delegate_to: "{{ groups['app-servers'][0] }}"
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"


