---
- name: Import IUS Community Project GPG key
  rpm_key:
    key: https://repo.ius.io/RPM-GPG-KEY-IUS-7
    state: present

- name: Install IUS repo.
  yum:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name:
      - "https://repo.ius.io/ius-release-el7.rpm"
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

- name: Remove PHP 5.x packages
  package:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: "php5*"
    state: absent

# Check if the desired version of PHP is installed. If it is not, ensure any
# other versions of PHP are not installed
- name: "Check if {{ php_ius_version }} package is installed"
  yum:
    list: "{{ php_ius_version }}-cli"
  register: correct_php

- debug:
    var: correct_php

- name: Set fact desired_PHP_version_installed
  set_fact:
    desired_PHP_version_installed: "{{ correct_php.results|selectattr('yumstate','match','installed')|list|length != 0 }}"

# PHP 7.3+ dropped the "u", e.g. php71u-cli vs php73-cli. Also, see note below about mod_php
- name: Remove php 7.x packages if correct PHP is not installed
  package:
    name: "*php7*"
    state: absent
  when: not desired_PHP_version_installed

- name: Ensure PHP IUS packages installed
  yum:
    name:
      # The following items exist in php56u, php70u, php71u, and php72u

      # There is no longer a plain "php73" package as there was a php71u. The
      # corresponding package is now called mod_php73.
      # - "{{ php_ius_version }}"
      - "mod_{{ php_ius_version }}"

      - "{{ php_ius_version }}-cli"
      - "{{ php_ius_version }}-common"
      - "{{ php_ius_version }}-devel"
      - "{{ php_ius_version }}-gd"
      - "{{ php_ius_version }}-pspell"
      - "{{ php_ius_version }}-snmp"
      - "{{ php_ius_version }}-xml"
      - "{{ php_ius_version }}-xmlrpc"
      - "{{ php_ius_version }}-mysqlnd"
      - "{{ php_ius_version }}-pdo"
      - "{{ php_ius_version }}-odbc"
      - "{{ php_ius_version }}-process"
      - "{{ php_ius_version }}-bcmath"
      - "{{ php_ius_version }}-intl"
      - "{{ php_ius_version }}-opcache"
      - "{{ php_ius_version }}-soap"
      - "{{ php_ius_version }}-mbstring"
      - "{{ php_ius_version }}-ldap"
      - "{{ php_ius_version }}-pecl-zip"

      # php56u has memcache and memcached; php7Xu only has memcached
      # legacy Meza used php56u-pecl-memcache
      - "{{ php_ius_version }}-pecl-memcached"

      # Available for php56u, php70u, and php71u. NOT for php72u.
      # - "php-mcrypt"

      # Available for php56u and php70u. NOT php71u or php72u
      # - "{{ php_ius_version }}-pear"

      # Post 7.0, use the pear1u package for all versions of PHP
      # PEAR is no longer a requirement for Meza. Mail and Net_SMTP installed with
      # Composer via MW core (MW 1.32+) or composer.local.json (MW 1.31 and lower)
      # However, PEAR is required for MSSQL integrations
      - pear1u

      # Not available for PHP 7, due to being built into PHP 7
      # - php56u-pecl-jsonc

      # Not available in PHP 7
      # Get alternative method of accessing SQL Server:
      # https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-red-hat-7
      # - php56u-mssql
    state: present
