---
- name: "Revoke keys from delegated server {{ revoke_keys_from_server }}"
  file:
    path: "/home/alt-meza-ansible/.ssh/{{ item }}"
    state: absent
  delegate_to: "{{ revoke_keys_from_server }}"
  with_items:
  - id_rsa
  - id_rsa.pub
