---

#
# Package names
#
package_firewall: ufw
package_openssh_client: openssh-client
package_cron: cron
package_apache: apache2
package_php_apache_deps: []

# Use Tokyo Cabinet for on-disk support if you know your distro supports it
# override with goaccess-tcb 
package_goaccess: goaccess
package_java: "default-jre"
package_python3: python3
package_python3_pip: python3-pip
package_base_extras:
  - expect
  - perl
  - wget
  - gcc
  - cifs-utils
  - curl
package_nmap: nmap
package_lua: [ 'liblua5.1-0-dev', 'liblua50-dev', 'liblualib50-dev', 're2c', 'pkg-config' ]


#
# Services
#
service_ntp: ntp
service_apache: apache2
service_cron: cron
service_ssh: ssh

#
# Paths
#
path_custom_pem_ca_trust: "/usr/local/share/ca-certificates/"
# Note: based on minimal research, Debian does not appear to use separate dirs for these
path_custom_extended_ca_trust: "/usr/local/share/ca-certificates/"
path_apache_conf: "/etc/apache2/apache2.conf"
path_apache_startup_config: "/etc/default/apache2"
path_apache_home: /usr/share/apache2
path_apache_server_root: "/etc/apache2"
path_php_conf_d: "/etc/php/{{ php_debian_version }}/cli/conf.d"
path_php_conf_d_files:
  - "10-opcache.ini"
path_php_apache_conf_d: "/etc/php/{{ php_debian_version }}/apache2/conf.d"
path_php_lib: "/usr/lib/php"
path_memcached_conf: "/etc/memcached.conf"


#
# Commands
#
command_update_ca_trust: "update-ca-certificates"


#
# Users and groups
#
user_apache: www-data
group_apache: www-data
user_memcached: memcache
