---
list:

  - name: Semantic MediaWiki
    composer: "mediawiki/semantic-media-wiki"
    version: "3.2.2"
    config: |
      // Enable Semantic MediaWiki semantics
      enableSemantics( $wikiId );

      // Semantic MediaWiki Settings
      $smwgQMaxSize = 5000;

      // allows adding semantic properties to Templates themselves
      // (not just on pages via templates).
      $smwgNamespacesWithSemanticLinks[NS_TALK] = true;
      $smwgNamespacesWithSemanticLinks[NS_TEMPLATE] = true;

      // Always use DB_REPLICA for temporary table actions. Need to pick either
      // DB_REPLICA or DB_MASTER for this, since temporary tables will either not
      // replicate at all or won't replicate fast enough (or, even if they do
      // technically replicate, they are only available to the session that
      // created them, and thus they effectively don't replicate). Picking
      // DB_REPLICA since temporary tables are effectively a read-action since
      // they are used only for making more efficient queries.
      $smwgLocalConnectionConf['mw.db.queryengine'] = [ 'read' => DB_REPLICA, 'write' => DB_REPLICA ];

  - name: Semantic Result Formats
    composer: "mediawiki/semantic-result-formats"
    version: "3.2.0"
    config: |
      // In SRF 3.0+ you need to do this, too:
      wfLoadExtension( 'SemanticResultFormats' );

      // SemanticResultFormats formats enabled (beyond defaults)
      // These are disabled by default because they send data to external
      // web services for rendering, which may be considered a data leak
      // $srfgFormats[] = 'googlebar';
      // $srfgFormats[] = 'googlepie';

      // Disabled until the proper dependencies are added (PHPExcel I think)
      // $srfgFormats[] = 'excel';

      // Enables the "filtered" format. Where do we use this?
      $srfgFormats[] = 'filtered';

      // Disabled due to some issue on FOD wikis. Confirm, reenable if possible
      // $srfgFormats[] = 'exhibit';

  - name: SemanticCompoundQueries
    composer: "mediawiki/semantic-compound-queries"
    version: "2.1.0"
    config: |
      wfLoadExtension( 'SemanticCompoundQueries' );

  - name: Scribunto
    repo: https://github.com/wikimedia/mediawiki-extensions-Scribunto.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgScribuntoDefaultEngine = 'luasandbox';
      $wgScribuntoUseGeSHi = true;
      $wgScribuntoUseCodeEditor = true;

  - name: "Semantic Scribunto"
    composer: "mediawiki/semantic-scribunto"
    version: "2.1.0"
    config: |
      wfLoadExtension( 'SemanticScribunto' );

  - name: SubPageList
    composer: "mediawiki/sub-page-list"
    version: "1.6.1"

  - name: Maps
    composer: "mediawiki/maps"
    version: "7.20.1" # FIXME this can bump to 8.x
    config: |
      // In Maps 6.0+ you need to also load the extension
      wfLoadExtension( 'Maps' );

  - name: DisplayTitle
    repo: https://github.com/wikimedia/mediawiki-extensions-DisplayTitle.git
    version: tags/2.1


  #
  # Extensions loaded with wfLoadExtension
  #
  - name: ParserFunctions
    repo: https://github.com/wikimedia/mediawiki-extensions-ParserFunctions.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      // Also enable StringFunctions, like len, pos, sub, replace, explode
      // https://www.mediawiki.org/wiki/Extension:StringFunctions
      $wgPFEnableStringFunctions = true;

  - name: ExternalData
    repo: https://github.com/wikimedia/mediawiki-extensions-ExternalData.git
    version: "tags/2.0.1"

  - name: LabeledSectionTransclusion
    repo: https://github.com/wikimedia/mediawiki-extensions-LabeledSectionTransclusion.git
    version: "{{ mediawiki_default_branch }}"

  - name: Cite
    repo: https://github.com/wikimedia/mediawiki-extensions-Cite.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgCiteEnablePopups = true;

  # Verify 34.x functionality
  - name: ParserFunctionHelper
    repo: https://github.com/enterprisemediawiki/ParserFunctionHelper.git
    version: tags/1.0.0

  - name: CharInsert
    repo: https://github.com/wikimedia/mediawiki-extensions-CharInsert.git
    version: "{{ mediawiki_default_branch }}"

  - name: PageForms
    repo: https://github.com/wikimedia/mediawiki-extensions-PageForms.git
    version: "tags/4.9.3"
    config: |
      // If enabled all "red links" will bring up a form chooser
      $wgPageFormsLinkAllRedLinksToForms = false;

  - name: DismissableSiteNotice
    repo: https://github.com/wikimedia/mediawiki-extensions-DismissableSiteNotice.git
    version: "{{ mediawiki_default_branch }}"

  - name: WikiEditor
    repo: https://github.com/wikimedia/mediawiki-extensions-WikiEditor.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgDefaultUserOptions['usebetatoolbar'] = 1;
      $wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
      $wgDefaultUserOptions['wikieditor-publish'] = 1; # displays publish button
      $wgDefaultUserOptions['wikieditor-preview'] = 1; # Displays the Preview and Changes tabs

  # consider replacing with https://github.com/wikimedia/mediawiki-extensions-SyntaxHighlight_Pygments.git
  - name: SyntaxHighlight_GeSHi
    repo: https://github.com/wikimedia/mediawiki-extensions-SyntaxHighlight_GeSHi.git
    version: "{{ mediawiki_default_branch }}"
    composer_merge: True

  - name: CodeEditor
    repo: https://github.com/wikimedia/mediawiki-extensions-CodeEditor.git
    version: "{{ mediawiki_default_branch }}"

  - name: InputBox
    repo: https://github.com/wikimedia/mediawiki-extensions-InputBox.git
    version: "{{ mediawiki_default_branch }}"

  - name: ReplaceText
    repo: https://github.com/wikimedia/mediawiki-extensions-ReplaceText.git
    version: tags/1.4.1

  - name: Interwiki
    repo: https://github.com/wikimedia/mediawiki-extensions-Interwiki.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgGroupPermissions['sysop']['interwiki'] = true;

  - name: YouTube
    repo: https://github.com/wikimedia/mediawiki-extensions-YouTube.git
    version: "{{ mediawiki_default_branch }}"

  - name: UniversalLanguageSelector
    repo: https://github.com/wikimedia/mediawiki-extensions-UniversalLanguageSelector
    version: "{{ mediawiki_default_branch }}"
    config: |
      // Disable international phoenetic alphabet selector that breaks searching for
      // English users. From docs:
      //
      // $wgULSIMEEnabled - Disable the input methods feature for all users by
      // default. Can still be enabled manually by the user.
      //
      // Refs:
      //
      // https://www.mediawiki.org/wiki/Help:Extension:UniversalLanguageSelector/Input_methods
      // https://www.mediawiki.org/wiki/Extension:UniversalLanguageSelector
      $wgULSIMEEnabled = false;

  - name: VisualEditor
    repo: https://github.com/wikimedia/mediawiki-extensions-VisualEditor.git
    version: "{{ mediawiki_default_branch }}"
    git_submodules: True
    config: |
      // Show visual diff on regular diff pages
      $wgVisualEditorEnableDiffPage = true;

      // Enable by default for everybody
      $wgDefaultUserOptions['visualeditor-enable'] = 1;

      // Don't allow users to disable it
      $wgHiddenPrefs[] = 'visualeditor-enable';

      // OPTIONAL: Enable VisualEditor's experimental code features
      // $wgDefaultUserOptions['visualeditor-enable-experimental'] = 1;

      $wgVisualEditorAvailableNamespaces = [
          "User" => true,
          "Project" => true,
          "Help" => true,
          "_merge_strategy" => "array_plus"
      ];

      // quickly add a namespace, without figuring out what the merge strategy is
      // $wgVisualEditorAvailableNamespaces[] = NS_CUSTOM;
      // $wgVisualEditorAvailableNamespaces[] = NS_PROJECT;

      $wgVirtualRestConfig['modules']['parsoid'] = array(
          'url' => "http://127.0.0.1/$wikiId/rest.php",
      );

      // Because we're manually setting the Virtual Rest Config above, need to load Parsoid manually
      wfLoadExtension( 'Parsoid', 'vendor/wikimedia/parsoid/extension.json' );

  - name: TemplateData
    repo: https://github.com/wikimedia/mediawiki-extensions-TemplateData.git
    version: "{{ mediawiki_default_branch }}"

  - name: Elastica
    repo: https://github.com/wikimedia/mediawiki-extensions-Elastica.git
    version: "{{ mediawiki_default_branch }}"
    composer_merge: True

  - name: Thanks
    repo: https://github.com/wikimedia/mediawiki-extensions-Thanks.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgThanksConfirmationRequired = false;

  - name: RevisionSlider
    repo: https://github.com/wikimedia/mediawiki-extensions-RevisionSlider.git
    version: "{{ mediawiki_default_branch }}"

  - name: CollapsibleVector
    repo: https://github.com/wikimedia/mediawiki-extensions-CollapsibleVector
    version: "{{ mediawiki_default_branch }}"

  - name: SimpleMathJax
    repo: https://github.com/jamesmontalvo3/SimpleMathJax.git
    version: e94afaffcdde8d926b166fdd166162f9519beaa1
    legacy_load: True

  - name: ImageMap
    repo: https://github.com/wikimedia/mediawiki-extensions-ImageMap
    version: "{{ mediawiki_default_branch }}"

  # Verify 34.x functionality
  - name: MezaExt
    repo: https://github.com/enterprisemediawiki/MezaExt.git
    version: tags/0.1.0

  # Extension:PdfHandler (breaks on very large PDFs)
  # https://github.com/wikimedia/mediawiki-extensions-PdfHandler
  # // Location of PdfHandler dependencies
  # // $wgPdfProcessor = '/usr/bin/gs'; // installed via yum
  # // $wgPdfPostProcessor = '/usr/local/bin/convert'; // built from source
  # // $wgPdfInfo = '/usr/local/bin/pdfinfo'; // pre-built binaries installed




  #
  # Extensions loaded with legacy require_once method
  #
  - name: StringFunctionsEscaped
    repo: https://github.com/wikimedia/mediawiki-extensions-StringFunctionsEscaped.git
    version: "{{ mediawiki_default_branch }}"
    legacy_load: true

  - name: WhoIsWatching
    repo: https://github.com/wikimedia/mediawiki-extensions-WhoIsWatching.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgPageShowWatchingUsers = true;

  - name: SemanticInternalObjects
    repo: https://github.com/wikimedia/mediawiki-extensions-SemanticInternalObjects.git
    # Latest version is 2016. Commit below is from 2020.
    version: "21a6af3b320160cbfbe97ba98604a1d334093e18"
    legacy_load: true

  - name: SemanticDrilldown
    repo: https://github.com/wikimedia/mediawiki-extensions-SemanticDrilldown.git
    version: "master"
    legacy_load: true

  - name: Arrays
    repo: https://github.com/wikimedia/mediawiki-extensions-Arrays.git
    version: "2166695159a9a5eb18cb96d4811cdefa0978ab8a"
    legacy_load: true

  # Verify 34.x functionality
  - name: TalkRight
    repo: https://github.com/enterprisemediawiki/TalkRight.git
    version: tags/2.0.0
    legacy_load: true

  - name: AdminLinks
    repo: https://github.com/wikimedia/mediawiki-extensions-AdminLinks.git
    version: "master"
    config: |
      $wgGroupPermissions['sysop']['adminlinks'] = true;

  - name: BatchUserRights
    repo: https://github.com/wikimedia/mediawiki-extensions-BatchUserRights.git
    version: "{{ mediawiki_default_branch }}"

  - name: HeaderTabs
    repo: https://github.com/wikimedia/mediawiki-extensions-HeaderTabs.git
    version: tags/1.2
    config: |
      $wgHeaderTabsEditTabLink = false;
      $wgHeaderTabsRenderSingleTab = true;

  # Verify 34.x functionality
  - name: CopyWatchers
    repo: https://github.com/jamesmontalvo3/MediaWiki-CopyWatchers.git
    version: tags/0.11.0

  # Verify 34.x functionality
  - name: Wiretap
    repo: https://github.com/enterprisemediawiki/Wiretap.git
    version: tags/0.2.0

  - name: ApprovedRevs
    repo: https://github.com/wikimedia/mediawiki-extensions-ApprovedRevs.git
    # Use this commit until a release tag for v1.0 is created
    version: tags/1.2.2
    config: |
      $egApprovedRevsAutomaticApprovals = false;

  # Verify 34.x functionality
  - name: ImagesLoaded
    repo: https://github.com/enterprisemediawiki/ImagesLoaded.git
    version: tags/0.1.0

  # Verify 34.x functionality
  - name: MasonryMainPage
    repo: https://github.com/enterprisemediawiki/MasonryMainPage.git
    version: tags/0.3.0

  # Verify 34.x functionality
  - name: WatchAnalytics
    repo: https://github.com/enterprisemediawiki/WatchAnalytics.git
    version: "master"   # FIXME set tag
    config: |
      $egPendingReviewsEmphasizeDays = 10; // makes Pending Reviews shake after X days

  - name: Variables
    repo: https://github.com/wikimedia/mediawiki-extensions-Variables.git
    version: "{{ mediawiki_default_branch }}"

  - name: ContributionScores
    repo: https://github.com/wikimedia/mediawiki-extensions-ContributionScores.git
    version: "{{ mediawiki_default_branch }}"
    legacy_load: true
    config: |
      // Exclude Bots from the reporting - Can be omitted.
      $wgContribScoreIgnoreBots = true;

      // Exclude Blocked Users from the reporting - Can be omitted.
      $wgContribScoreIgnoreBlockedUsers = true;

      // Use real user names when available - Can be omitted. Only for MediaWiki 1.19 and later.c
      $wgContribScoresUseRealName = true;

      // Set to true to disable cache for parser function and inclusion of table.
      $wgContribScoreDisableCache = false;

      // Each array defines a report - 7,50 is "past 7 days" and "LIMIT 50" - Can be omitted.
      $wgContribScoreReports = array(
        array(7,50),
        array(30,50),
        array(0,50)
      );

  - name: SemanticExtraSpecialProperties
    composer: "mediawiki/semantic-extra-special-properties"
    version: "2.0.0"
  - name: PipeEscape
    repo: https://github.com/wikimedia/mediawiki-extensions-PipeEscape.git
    version: "{{ mediawiki_default_branch }}"
    legacy_load: true

  - name: CirrusSearch
    repo: https://github.com/wikimedia/mediawiki-extensions-CirrusSearch.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      // CirrusSearch cluster(s) are defined based upon Ansible hosts file and thus
      // cannot be easily added to MezaCoreExtensions.yml. As such, CirrusSearch config
      // is included directly in LocalSettings.php.j2

  - name: Echo
    repo: https://github.com/wikimedia/mediawiki-extensions-Echo.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgEchoEmailFooterAddress = $wgPasswordSender;

  - name: UploadWizard
    repo: https://github.com/wikimedia/mediawiki-extensions-UploadWizard
    version: "{{ mediawiki_default_branch }}"
    config: |
      // Needed to make UploadWizard work in IE, see bug 39877
      // See also: https://www.mediawiki.org/wiki/Manual:$wgApiFrameOptions
      $wgApiFrameOptions = 'SAMEORIGIN';

      // Use UploadWizard by default in navigation bar
      $wgUploadNavigationUrl = "$wgScriptPath/index.php/Special:UploadWizard";
      $wgUploadWizardConfig = array(
        'debug' => false,
        'autoCategory' => 'Uploaded with UploadWizard',
        'feedbackPage' => 'Project:UploadWizard/Feedback',
        'altUploadForm' => 'Special:Upload',
        'fallbackToAltUploadForm' => false,
        'enableFormData' => true,  # Should FileAPI uploads be used on supported browsers?
        'enableMultipleFiles' => true,
        'enableMultiFileSelect' => true,
        'tutorial' => array('skip' => true),
        'fileExtensions' => $wgFileExtensions, //omitting this can cause errors
        'licensing' => array(
          // alternatively, use "thirdparty". Set in postLocalSettings.php like:
          // $wgUploadWizardConfig['licensing']['defaultType'] = 'thirdparty';
          'defaultType' => 'ownwork',

          'ownWork' => array(
            'type' => 'or',
            // Use [[Project:General disclaimer]] instead of default [[Template:Generic]]
            'template' => 'Project:General disclaimer',
            'defaults' => array( 'generic' ),
            'licenses' => array( 'generic' )
          ),

          'thirdParty' => array(
            'type' => 'or',
            'defaults' => array( 'generic' ),
            'licenseGroups' => array(
              array(
                'head' => 'mwe-upwiz-license-generic-head',
                'template' => 'Project:General disclaimer', // again, use General disclaimer
                'licenses' => array( 'generic' ),
              ),
            )
          ),
        ),
      );

  - name: DataTransfer
    repo: https://github.com/wikimedia/mediawiki-extensions-DataTransfer.git
    version: "tags/1.1.1"

  - name: PageImporter
    repo: https://github.com/enterprisemediawiki/PageImporter.git
    version: tags/0.1.0
    legacy_load: True

  # Verify 34.x functionality
  - name: SemanticMeetingMinutes
    repo: https://github.com/enterprisemediawiki/SemanticMeetingMinutes.git
    version: tags/1.0.0
    legacy_load: True

  # Verify 34.x functionality
  - name: HeaderFooter
    repo: https://github.com/enterprisemediawiki/HeaderFooter.git
    version: tags/3.0.1

  - name: NumerAlpha
    repo: https://github.com/wikimedia/mediawiki-extensions-NumerAlpha.git
    version: tags/0.7.0
    legacy_load: True
