---

#
# Package names
#
package_firewall: firewalld
package_openssh_client: openssh-clients
package_cron: cronie
package_apache: httpd-devel
package_php_apache_deps7:
  - sendmail
  - sendmail-cf
  - m4
  - xz-libs
  - mariadb-libs
  - zlib-devel
package_php_apache_deps8:
  - sendmail
  - sendmail-cf
  - m4
  - xz-libs
  - zlib-devel
package_java: java-1.8.0-openjdk
package_python3: python36
package_python3_pip: python36-pip
package_python3_pip_rhel8: python3-pip
package_base_extras7:
  - expect
  - expectk
  - perl
  - wget
  - gcc
  - cifs-utils
package_base_extras8:
  - expect
  - perl
  - wget
  - gcc
  - cifs-utils
package_nmap: nmap-ncat
package_lua: [ 'lua', 'lua-devel' ]
package_imagemagick:
  - ghostscript
  - ImageMagick
package_ntp: ntpd
package_ntp8: chrony

#
# Services
#
service_ntp: ntpd
service_ntp8: chronyd
service_apache: httpd
service_cron: crond
service_ssh: sshd
service_php_fpm: php-fpm

#
# Paths
#
path_custom_pem_ca_trust: "/etc/pki/ca-trust/source/anchors/"
path_custom_extended_ca_trust: "/etc/pki/ca-trust/source/"
path_apache_conf: /etc/httpd/conf/httpd.conf
path_apache_startup_config: "/etc/sysconfig/httpd"
path_apache_home: /usr/share/httpd
path_apache_server_root: "/etc/httpd"
path_php_conf_d: "/etc/php.d/"
path_php_conf_d_files:
  - "10-opcache.ini"
path_php_apache_conf_d: "/etc/php.d"
path_php_lib: "/usr/lib64/php"
# was: m_memcached_conf: /etc/sysconfig/memcached
path_memcached_conf: /etc/sysconfig/memcached
path_php_fpm_conf: /etc/php-fpm.d/www.conf
path_php_httpd_conf: /etc/httpd/conf.d/php.conf

#
# Commands
#
command_update_ca_trust: "update-ca-trust"


#
# Users and groups
#
user_apache: apache
group_apache: apache
user_memcached: memcached
