---

- name: Ensure secret config directory exists
  file:
    path: "{{ m_local_secret }}"
    state: directory
    owner: meza-ansible
    group: wheel
    mode: 0750

- name: Ensure secret config environment directory exists
  file:
    path: "{{ m_local_secret }}/{{ env }}"
    state: directory
    owner: meza-ansible
    group: wheel
    mode: 0750

- name: Ensure group_vars directory exists
  file:
    path: "{{ m_local_secret }}/{{ env }}/group_vars"
    state: directory
    owner: meza-ansible
    group: wheel
    mode: 0750

# Ansible writing Ansible
- name: Ensure hosts file configured
  template:
    src: hosts.j2
    dest: "{{ m_local_secret }}/{{ env }}/hosts"
    owner: meza-ansible
    group: wheel
    mode: 0640

    # We don't want to overwrite an existing hosts file with the default
    force: no

- name: Ensure all.yml configured
  template:
    src: all.yml.j2
    dest: "{{ m_local_secret }}/{{ env }}/group_vars/all.yml"
    owner: meza-ansible
    group: wheel
    mode: 0640

    # don't overwrite existing
    force: no
