---
- name: Ensure ghostscript installed
  yum: name=ghostscript state=installed
- name: Install Imagemagick from meza repo
  yum: name=https://raw.github.com/enterprisemediawiki/meza-packages/master/RPMs/imagemagick_7.0.3_x86_64.rpm
- name: Symlink xpdf bin64 files to /usr/local/bin
  copy:
    src: xpdf-3.04-bin64/
    dest: /usr/local/bin/
