---
# Simple playbook to make sure config.sh, config.php, and any other simple
# config scripts like them can be quickly deployed to servers.

- hosts: all:!exclude-all:!load_balancers_nonmeza:!load_balancers_nonmeza_external:!load_balancers_nonmeza_internal
  become: yes
  roles:
    - set-vars
    - umask-set
    - base-config-scripts
    - umask-unset
