---
list:

- name: Vector
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/skins/Vector.git
  type: skins
  version: "{{ mediawiki_default_branch }}"

# 
# If you'd like to use any of these skins it is recommended that these lines
# be placed in /opt/conf-public/public/MezaLocalSkins.yml
#
#- name: Modern
#  repo: https://gerrit.wikimedia.org/r/p/mediawiki/skins/Modern.git
#  type: skins
#  version: "{{ mediawiki_default_branch }}"
#
#- name: CologneBlue
#  repo: https://gerrit.wikimedia.org/r/p/mediawiki/skins/CologneBlue.git
#  type: skins
#  version: "{{ mediawiki_default_branch }}"
#
#- name: MonoBook
#  repo: https://gerrit.wikimedia.org/r/p/mediawiki/skins/MonoBook.git
#  type: skins
#  version: "{{ mediawiki_default_branch }}"
