---

# meza install location
m_install: /opt
m_meza: /opt/meza

# config dir
m_config: /opt/meza/config
m_local_secret: /opt/meza/config/local-secret
m_local_public: /opt/meza/config/local-public
m_local_app: /opt/meza/config/local_app

# Config files written by Ansible which need a place to live. See README.md in
# this directory for more info.
m_config_app_ansible: /opt/meza/config/core/app-ansible

# scripts dir
m_scripts: /opt/meza/src/scripts

# test dir
m_test: /opt/meza/test

# data dir
m_meza_data: /opt/meza/data
m_tmp: /opt/meza/data/tmp

# uploads dir. In order to support both app-server-based uploads and
# GlusterFS-based uploads (or other alternatives) it may be necessary to be
# able to specify this path, with options like:
#   - /opt/meza/data/uploads    (app-server based)
#   - /opt/meza/data/glusterfs  (GlusterFS based)
#   - /opt/meza/data/other (something really cool that I don't even know about)
m_uploads_dir: /opt/meza/data/uploads

# Location where backups will go, specified by environment, e.g.
# /opt/meza/data/backups/prod for "prod" environment
m_backups: /opt/meza/data/backups

# webserver variables
m_htdocs: /opt/meza/htdocs
m_mediawiki: /opt/meza/htdocs/mediawiki
m_cert_private: /etc/pki/tls/private/meza.key
m_cert_public: /etc/pki/tls/certs/meza.crt
m_ca_cert: /etc/pki/tls/certs/meza-ca.crt


# app locations
m_apache: /etc/httpd
m_apache_conf: /etc/httpd/conf/httpd.conf
m_php_ini: /etc/php.ini
m_memcached_conf: /etc/sysconfig/memcached
m_parsoid_path: /etc/parsoid
m_simplesamlphp_path: /opt/simplesamlphp

# files
m_local_config_file: /opt/meza/config/local/config.local.sh
m_i18n: /opt/meza/config/core/i18n
m_db_replication_dump_file: /opt/meza/data/db_master_for_replication.sql
m_db_replication_log_file: /opt/meza/data/db_master_log_file
m_db_replication_log_pos: /opt/meza/data/db_master_log_pos


# FIXME: this is not a "path" but it's the best place to keep it for now
# Set Parsoid version.
# This commit is closest to MW 1.27 release date of 28 June 2016
# Default = "master"
m_parsoid_version: dd8e644d320aec076f76da4e2bd70a8527e0dfd8
