---

#
# Package names
#
package_firewall: firewalld
package_openssh_client: openssh-clients
package_cron: cronie
package_apache: httpd-devel
package_php_apache_deps:
  - zlib-devel
  - sqlite-devel
  - bzip2-devel
  - pcre-devel
  - openssl-devel
  - curl-devel
  - libxml2-devel
  - libXpm-devel
  - gmp-devel
  - libicu-devel
  - t1lib-devel
  - aspell-devel
  - libcurl-devel
  - libjpeg-devel
  - libvpx-devel
  - libpng-devel
  - freetype-devel
  - readline-devel
  - libtidy-devel
  - libmcrypt-devel
  - pam-devel
  - sendmail
  - sendmail-cf
  - m4
  - xz-libs
  - mariadb-libs
package_java: java-1.8.0-openjdk
package_python3: python35u
package_base_extras:
  - expect
  - expectk
  - perl
  - wget
  - gcc
  - cifs-utils
package_nmap: nmap-ncat

#
# Services
#
service_ntp: ntpd
service_apache: httpd

#
# Paths
#
path_custom_pem_ca_trust: "/etc/pki/ca-trust/source/anchors/"
path_custom_extended_ca_trust: "/etc/pki/ca-trust/source/"
path_apache_conf: /etc/httpd/conf/httpd.conf
path_apache_startup_config: "/etc/sysconfig/httpd"
path_apache_home: /usr/share/httpd
path_apache_server_root: "/etc/httpd"
path_php_conf_d: "/etc/php.d/"
path_php_conf_d_files:
  - "10-opcache.ini"
# was: m_memcached_conf: /etc/sysconfig/memcached
path_memcached_conf: /etc/sysconfig/memcached


#
# Commands
#
command_update_ca_trust: "update-ca-trust"


#
# Users and groups
#
user_apache: apache
group_apache: apache
