---
- name: ParserFunctions
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ParserFunctions.git
  version: REL1_27
- name: StringFunctionsEscaped
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/StringFunctionsEscaped.git
  version: REL1_27
- name: ExternalData
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ExternalData.git
  version: REL1_27
- name: LabeledSectionTransclusion
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/LabeledSectionTransclusion.git
  version: REL1_27
- name: Cite
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Cite.git
  version: REL1_27
- name: ParserFunctionHelper
  repo: https://github.com/enterprisemediawiki/ParserFunctionHelper.git
  version: master
- name: WhoIsWatching
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/WhoIsWatching.git
  version: REL1_27
- name: CharInsert
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CharInsert.git
  version: REL1_27
- name: SemanticForms
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SemanticForms.git
  version: tags/3.5
- name: SemanticInternalObjects
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SemanticInternalObjects.git
  version: REL1_27
- name: SemanticCompoundQueries
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SemanticCompoundQueries.git
  version: REL1_27
- name: Arrays
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Arrays.git
  version: REL1_27
- name: TalkRight
  repo: https://github.com/enterprisemediawiki/TalkRight.git
  version: extreg
- name: AdminLinks
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/AdminLinks.git
  version: REL1_27
- name: DismissableSiteNotice
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/DismissableSiteNotice.git
  version: REL1_27
- name: BatchUserRights
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/BatchUserRights.git
  version: REL1_27
- name: HeaderTabs
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/HeaderTabs.git
  version: REL1_27
- name: WikiEditor
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/WikiEditor.git
  version: REL1_27
- name: CopyWatchers
  repo: https://github.com/jamesmontalvo3/MediaWiki-CopyWatchers.git
  version: extreg
- name: SyntaxHighlight_GeSHi
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SyntaxHighlight_GeSHi.git
  version: REL1_27
- name: Wiretap
  repo: https://github.com/enterprisemediawiki/Wiretap.git
  version: extreg
- name: ApprovedRevs
  repo: https://github.com/jamesmontalvo3/MediaWiki-ApprovedRevs.git
  version: master
- name: InputBox
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/InputBox.git
  version: REL1_27
- name: ReplaceText
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ReplaceText.git
  version: REL1_27
- name: Interwiki
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Interwiki.git
  version: REL1_27
- name: MasonryMainPage
  repo: https://github.com/enterprisemediawiki/MasonryMainPage.git
  version: extreg
- name: WatchAnalytics
  repo: https://github.com/enterprisemediawiki/WatchAnalytics.git
  version: master
- name: Variables
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Variables.git
  version: REL1_27
- name: YouTube
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/YouTube.git
  version: REL1_27
- name: ContributionScores
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ContributionScores.git
  version: REL1_27

# @todo: The "official" version of this is in an SVN repository. If we need
#        this it should be migrated to Gerrit or an EMW managed git repo.
#        See https://www.mediawiki.org/wiki/Extension:Pipe_Escape
- name: PipeEscape
  repo: https://github.com/jamesmontalvo3/MediaWiki-PipeEscape.git
  version: extreg
- name: UniversalLanguageSelector
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UniversalLanguageSelector.git
  version: REL1_27
- name: VisualEditor
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/VisualEditor.git
  version: REL1_27
- name: Elastica
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Elastica.git
  version: REL1_27
- name: CirrusSearch
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CirrusSearch.git
  version: REL1_27
- name: Echo
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Echo.git
  version: REL1_27
- name: Thanks
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Thanks.git
  version: REL1_27
- name: UploadWizard
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/UploadWizard
  version: REL1_27
- name: CollapsibleVector
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CollapsibleVector
  version: REL1_27
- name: Math
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Math.git
  version: REL1_27
- name: DataTransfer
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DataTransfer.git
  version: tags/0.6.2
