---
- name: Set up the Nodesource RPM directory for Node.js > 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub_{{ nodejs_version }}"
  when: nodejs_version != '0.10'

- name: Set up the Nodesource RPM variable for Node.js == 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub"
  when: nodejs_version == '0.10'

- name: Import Nodesource RPM key (CentOS < 7).
  rpm_key:
    key: http://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version|int < 7

- name: Import Nodesource RPM key (CentOS 7+)..
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version|int >= 7

- name: Add Nodesource repositories for Node.js (CentOS < 7).
  yum:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: "http://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version|int < 7

- name: Add Nodesource repositories for Node.js (CentOS 7+).
  yum:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: "https://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version|int >= 7

# Fix for RHEL upgrade from 7.3 --> 7.4 adding package http-parser to base
# repository, which caused it to be removed from the EPEL repository. When
# CentOS 7.4 comes out it will have http-parser in its base repo. To maintain
# functionality for all machines running RHEL/CentOS 7.0-7.3 we need to
# manually install http-parser.
#
# Refs:
#   https://bugs.centos.org/view.php?id=13669&nbn=8
#   https://bugzilla.redhat.com/show_bug.cgi?id=1481008
#   https://bugzilla.redhat.com/show_bug.cgi?id=1481470
- name: Ensure http-parser installed from RPM for {{ ansible_distribution_version }}
  yum:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
    state: present
  when: ansible_distribution_version.split('.')[1] | int <= 3

- name: Ensure Node.js and npm are installed.
  yum:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: "nodejs-{{ nodejs_version[0] }}.*"
    state: present
    enablerepo: 'epel,nodesource'"
