---
- hosts: all
  become: true
  vars:
    ntp_server: [0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org, 3.pool.ntp.org]
  tasks:
  - name: ensure deltarpm is installed and latest
    yum: name=deltarpm state=installed
  - name: upgrade all packages
    yum: name=* state=latest
  # FIXME: for RedHat may need to enable "Optional RPMs"
  - name: ensure EPEL installed
    yum: name=epel-release state=installed
  - name: ensure libselinux-python installed prior to SELinux
    yum: name=libselinux-python state=installed
  - name: put SELinux in permissive mode
    selinux:
      policy: targeted
      state: permissive # log actions that would be blocked if state=enforcing
  - name: Install base packages
    yum: name={{item}} state=installed
    with_items:
      - ntp
      - ntpdate
      - ntp-doc
      - openssh-server
      - openssh-clients
      - vim
      - net-tools
      - firewalld
  - name: ensure firewalld is running (and enable it at boot)
    service: name=firewalld state=started enabled=yes

  # Replace the following shell commands:
  # chkconfig ntpd on # Activate service
  # ntpdate pool.ntp.org # Synchronize the system clock with 0.pool.ntp.org server
  # service ntpd start # Start service
  - name: Install NTP
    yum: name=ntp state=installed
  - name: Ensure NTP is running and enabled as configured.
    service:
      name: ntpd
      state: started
      enabled: yes
  - name: Copy the ntp.conf template file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
      - restart ntpd
  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted

