---
- name: Install memcached package
  yum: name=memcached state=installed
- name: write the memcached config file
  template: "src=memcached.j2 dest={{ m_memcached_conf }}"
  notify:
  - restart memcached
- name: ensure memcached is running (and enable it at boot)
  service: name=memcached state=started enabled=yes
  when: docker_skip_tasks is not defined or not docker_skip_tasks
