---

# Setup user? See
# https://github.com/geerlingguy/ansible-role-memcached/blob/master/tasks/main.yml

- name: Ensure memcached and netcat packages latest
  yum:
    name:
      - memcached
      - "{{ package_nmap }}"
    state: latest
  tags:
    - latest

- name: Write the memcached config file
  template:
    src: memcached.j2
    dest: "{{ path_memcached_conf }}"
  notify:
  - restart memcached

- name: Ensure memcached is running (and enable it at boot)
  service:
    name: memcached
    state: started
    enabled: yes
  when: docker_skip_tasks is not defined or not docker_skip_tasks
